name: Node.js CI

on:
  push:
    branches:
      - main  # Change this to your main branch if necessary
  pull_request:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NVM and Node.js 20
        run: |
          # Install NVM
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          source $HOME/.nvm/nvm.sh
          
          # Install and use Node.js 20
          nvm install 20
          nvm use 20

      - name: Install dependencies
        run: |
          # Install dependencies, including play-dl
          npm install
          npm install play-dl  # Ensure play-dl is installed explicitly

      - name: Run the bot
        run: npm start